### PR TITLE
Victor/nft 647 Add properties to whoopi

### PR DESCRIPTION
**Pull request by victonesha**
- added userShare parameter for Lendings 
- added isAvailable parameter for Lendings

### CODE REVIEW

**Comment by victonesha** [comment]
I see that a lot of layout changes happened. I will propose some Linting rules for this together with the BE tomorrow morning.

**Comment by nazariyv** [comment]
did you check this out on your own the graph account if it indexes fully well? It costs money to update subgraphs in prod.

**Comment by victonesha** [comment]
I'm doing it now and will be back with the result @nazariyv

**Comment by bauti-defi** [comment]
Looks good to me!

**Comment by victonesha** [comment]
The subgraph has been deployed on my account and @jeffrey-dot-li confirmed this is what he was looking for. Me and @bauti-defi also played a bit with it, so we will consider it good to go.

**Pull request closed without merging**
